volumes:
  postgres_vol:

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pgpw
      POSTGRES_DB: sakura
    ports:
      - 5432:5432
    volumes:
      - postgres_vol:/var/lib/postgresql
