spring:
  application:
    name: gatewayapi
  datasource:
    url: jdbc:postgresql://localhost:5432/sakura
    username: ${DB_USERNAME:pg}
    password: ${DB_PASSWORD:pgpw}
  jpa:
    hibernate:
      ddl-auto: validate

sakura:
  storage:
    images-path: ${IMAGES_PATH:/tmp/sakura/images}
  security:
    username: ${UPLOAD_USERNAME:admin}
    password: ${UPLOAD_PASSWORD:changeme}
