@startuml
left to right direction

person C [
<b>Cliente</b>
[Person]
---
Fornecedor dos dados.
]

rectangle E [
<b>Email Service</b>
[Software System]
---
Serviço de email.
]

rectangle S [
<b>Sakura</b>
[Software System]
---
Recebe dados do cliente, 
os processa e devolve a informação. 
]

rectangle VIA [
<b>Vision LLM</b>
[Software System]
---
Serviços de IA para imagem.
]

C ..> S : Envia imagem\ndo Cupom Fiscal
S ..> VIA : Transforma imagem em texto
S ..> E : Envia email com informação
E ..> C : Notifica usuário
@enduml
