@startuml
left to right direction

person C [
<b>Cliente</b>
[Person]
---
Fornecedor dos dados.
]

rectangle E [
<b>Email Service</b>
[Software System]
---
Serviço de email.
]

rectangle Sakura as S {
    rectangle B [
    <b>Backend</b>
    [Container: Java and Spring Boot]
    ---
    Recebe mensagens do cliente.
    ]

    database DB [
    <b>Database</b>
    [Container: Postgres]
    ---
    Todos os registros.
    ]

    database FS [
    <b>Filesystem</b>
    [Container: Filesystem]
    ---
    Imagens.
    ]
}

rectangle VIA [
<b>LLM</b>
[Software System]
---
Serviços de IA para imagem.
]

C ..> B : Envia imagem\ndo Cupom Fiscal
B ..> VIA : Transforma imagem em texto e faz previsão
B ..> DB : Salva e lê dados
B ..> FS : Salva e lê dados
B ..> E : Envia email com informação
E ..> C : Notifica usuário
@enduml
